name: ci
on: push
jobs:
  test:
    environment: development
    runs-on: ubuntu-22.04
    container: tyknkd/spark:3.3.2-scala2.13-jdk17-gradle8.7-jammy
    env:
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      POSTGRES_USER: newsanalyzer
      POSTGRES_DB: collector_db
      OS_ENV: container
    services:
      db:
        image: postgres:16.2
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      mq:
        image: rabbitmq:3.13-management
        ports:
          - 5672:5672
          - 15692:15692
        options: >-
          --health-cmd "rabbitmq-diagnostics check_port_connectivity"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load environment variables
        run: source .env

      - name: Create additional databases
        run: ./docker-databases/docker-entrypoint-initdb.d/init-additional-db.sh

      - name: Run unit and integration tests
        run: gradle test