apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-configmap
data:
  init-additional-db.sh: |
    #!/bin/sh

    set -e  # Exit script immediately if command exits with non-zero status
    IFS=',' # Internal field separator

    for database in $ADDITIONAL_POSTGRES_DB; do
      echo "Creating database: '$database'"
      psql -v ON_ERROR_STOP=1 --host "$POSTGRES_HOST" --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -c "create database $database"
    done
