apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  clusterIP: None
  ports:
    - name: grafana-port
      port: 3000
      targetPort: 3000
  selector:
    app: grafana
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: grafana
  serviceName: grafana-service
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana-oss:10.4.2
          env:
            - name: GF_FEATURE_TOGGLES_ENABLE
              value: publicDashboards
            - name: GF_SECURITY_ADMIN_PASSWORD__FILE
              value: /run/secrets/grafana-password
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /run/secrets/grafana-password
              name: grafana-password
              subPath: grafana-password
            - mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
              name: grafana-datasources
              subPath: datasources.yaml
            - mountPath: /etc/grafana/provisioning/dashboards/providers.yaml
              name: grafana-providers
              subPath: providers.yaml
            - mountPath: /var/lib/grafana/dashboards/dashboard.json
              name: grafana-dashboard
              subPath: dashboard.json
            - mountPath: /var/lib/grafana
              name: grafana-claim
      restartPolicy: Always
      volumes:
        - name: postgres-password
          secret:
            items:
              - key: postgres-password
                path: postgres-password
            secretName: postgres-password-secret
        - name: grafana-datasources
          configMap:
            name: grafana-datasources-configmap
        - name: grafana-providers
          configMap:
            name: grafana-providers-configmap
        - name: grafana-dashboard
          configMap:
            name: grafana-dashboard-configmap
  volumeClaimTemplates:
    - metadata:
        name: grafana-claim
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
