apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: newsanalyzer-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: newsanalyzer-ip
spec:
  defaultBackend:
    service:
      name: web-server
      port:
        number: 8888