apiVersion: v1
kind: Service
metadata:
  name: mq
spec:
  clusterIP: None
  ports:
    - name: mq-port
      port: 5672
      targetPort: 5672
    - name: mq-metrics-port
      port: 15692
      targetPort: 15692
  selector:
    app: mq
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mq-sts
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: mq
  serviceName: mq
  template:
    metadata:
      labels:
        app: mq
    spec:
      containers:
        - name: mq
          image: rabbitmq:3.13-management
          env:
            - name: RABBITMQ_DEFAULT_PASS
              value: /run/secrets/mq-password
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_DEFAULT_USER
                  name: env
            - name: RABBITMQ_LOGS
              value: "-"
          ports:
            - containerPort: 5672
            - containerPort: 15692
          volumeMounts:
            - mountPath: /run/secrets/mq-password
              name: mq-password
              subPath: mq-password
            - mountPath: /etc/rabbitmq
              name: mq-plugins
            - mountPath: /var/lib/rabbitmq
              name: mq-claim
      restartPolicy: Always
      volumes:
        - name: mq-password
          secret:
            items:
              - key: mq-password
                path: mq-password
            secretName: mq-password-secret
        - name: mq-plugins
          configMap:
            name: mq-plugins-configmap
  volumeClaimTemplates:
    - metadata:
        name: mq-claim
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
