apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
data:
  prometheus.yml: |-
    global:
      scrape_interval: 10s

    scrape_configs:
      - job_name: 'web-server'
        metrics_path: /metrics
        scrape_interval: 10s
        static_configs:
          - targets: [ 'web-server-service:8888' ]
      - job_name: 'data-analyzer'
        metrics_path: /metrics
        scrape_interval: 10s
        static_configs:
          - targets: [ 'data-analyzer-service:8887' ]
      - job_name: 'data-collector'
        metrics_path: /metrics
        scrape_interval: 10s
        static_configs:
          - targets: [ 'data-collector-service:8886' ]
      - job_name: 'rabbitmq'
        metrics_path: /metrics
        scrape_interval: 10s
        static_configs:
          - targets: [ 'mq-service:15692' ]
