apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
data:
  prometheus.yml: |-
    global:
      scrape_interval: 60s

    scrape_configs:
      - job_name: 'web-server'
        metrics_path: /metrics
        scrape_interval: 60s
        static_configs:
          - targets: [ 'web-server:8888' ]
      - job_name: 'data-analyzer'
        metrics_path: /metrics
        scrape_interval: 60s
        static_configs:
          - targets: [ 'data-analyzer:8887' ]
      - job_name: 'data-collector'
        metrics_path: /metrics
        scrape_interval: 60s
        static_configs:
          - targets: [ 'data-collector:8886' ]
      - job_name: 'rabbitmq'
        metrics_path: /metrics
        scrape_interval: 60s
        static_configs:
          - targets: [ 'mq:15692' ]
