apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image: tyknkd/newsanalyzer-webserver
          env:
            - name: ANALYZER_EXCHANGE
              valueFrom:
                configMapKeyRef:
                  key: ANALYZER_EXCHANGE
                  name: env
            - name: ANALYZER_HOST
              valueFrom:
                configMapKeyRef:
                  key: ANALYZER_HOST
                  name: env
            - name: ANALYZER_QUEUE
              valueFrom:
                configMapKeyRef:
                  key: ANALYZER_QUEUE
                  name: env
            - name: ANALYZER_ROUTING_KEY
              valueFrom:
                configMapKeyRef:
                  key: ANALYZER_ROUTING_KEY
                  name: env
            - name: COLLECTOR_HOST
              valueFrom:
                configMapKeyRef:
                  key: COLLECTOR_HOST
                  name: env
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: env
            - name: POSTGRES_PASSWORD_FILE
              value: /run/secrets/postgres-password
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_HOST
                  name: env
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_PORT
                  name: env
            - name: WEBSERVER_DB
              valueFrom:
                configMapKeyRef:
                  key: WEBSERVER_DB
                  name: env
            - name: WEBSERVER_HOST
              valueFrom:
                configMapKeyRef:
                  key: WEBSERVER_HOST
                  name: env
            - name: WEBSERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: WEBSERVER_PORT
                  name: env
          ports:
            - containerPort: 8888
              hostPort: 8888
              protocol: TCP
          volumeMounts:
            - mountPath: /run/secrets/postgres-password
              name: postgres-password
              subPath: postgres-password
      restartPolicy: Always
      volumes:
        - name: postgres-password
          secret:
            items:
              - key: postgres-password
                path: postgres-password
            secretName: postgres-password-secret
---
apiVersion: v1
kind: Service
metadata:
  name: web-server-service
spec:
  ports:
    - name: web-port
      port: 8888
      targetPort: 8888
  selector:
    app: web-server