apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      initContainers:
        - name: await-db
          image: busybox
          command: [ "sh", "-c", "until nc -z db:5432; do echo 'waiting for db'; sleep 5; done;" ]
        - name: await-mq
          image: busybox
          command: [ "sh", "-c", "until nc -z mq:5672; do echo 'waiting for mq'; sleep 5; done;" ]
      containers:
        - name: web-server
          image: tyknkd/newsanalyzer-webserver:0.1.1
          env:
            - name: ANALYZER_EXCHANGE
              valueFrom:
                configMapKeyRef:
                  key: ANALYZER_EXCHANGE
                  name: env
            - name: ANALYZER_HOST
              valueFrom:
                configMapKeyRef:
                  key: ANALYZER_HOST
                  name: env
            - name: ANALYZER_QUEUE
              valueFrom:
                configMapKeyRef:
                  key: ANALYZER_QUEUE
                  name: env
            - name: ANALYZER_ROUTING_KEY
              valueFrom:
                configMapKeyRef:
                  key: ANALYZER_ROUTING_KEY
                  name: env
            - name: COLLECTOR_HOST
              valueFrom:
                configMapKeyRef:
                  key: COLLECTOR_HOST
                  name: env
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: env
            - name: POSTGRES_PASSWORD_FILE
              value: /run/secrets/postgres-password
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
            - name: RABBITMQ_DEFAULT_PASS
              value: /run/secrets/mq-password
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_DEFAULT_USER
                  name: env
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_HOST
                  name: env
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_PORT
                  name: env
            - name: WEBSERVER_DB
              valueFrom:
                configMapKeyRef:
                  key: WEBSERVER_DB
                  name: env
            - name: WEBSERVER_HOST
              valueFrom:
                configMapKeyRef:
                  key: WEBSERVER_HOST
                  name: env
            - name: WEBSERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: WEBSERVER_PORT
                  name: env
          ports:
            - containerPort: 8888
          volumeMounts:
            - mountPath: /run/secrets/mq-password
              name: mq-password
              subPath: mq-password
            - mountPath: /run/secrets/postgres-password
              name: postgres-password
              subPath: postgres-password
      restartPolicy: Always
      volumes:
        - name: mq-password
          secret:
            items:
              - key: mq-password
                path: mq-password
            secretName: mq-password-secret
        - name: postgres-password
          secret:
            items:
              - key: postgres-password
                path: postgres-password
            secretName: postgres-password-secret
---
apiVersion: v1
kind: Service
metadata:
  name: web-server
spec:
  ports:
    - name: web-port
      port: 8888
      targetPort: 8888
  selector:
    app: web-server