{
 "title": "News Analyzer Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM Live Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ktor_http_server_requests_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request 404 Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "ktor_http_server_requests_seconds_count{status=\"404\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Delivered Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rabbitmq_global_messages_delivered_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unroutable Dropped Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rabbitmq_global_messages_unroutable_dropped_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}